# -*- coding: utf-8 -*-
"""2_Beta_distribution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IjZqBqRsSYo1LUSiSSnS_HLDoCVur4kD
"""

import numpy as np
from scipy.special import gamma
import matplotlib.pyplot as plt

def fact(a):

    if a==1 or a==0:
        return 1
    return a*fact(a-1)
def beta_distribution(a,b,x):
    
    ans = []
    normalizing = fact(a+b-1)/(fact(a-1)*fact(b-1))
    for i in range(len(x)):
        ans.append((x[i]**(a-1))*((1-x[i])**(b-1)))
    return normalizing*np.array(ans)
x = np.linspace(0,1,500)
beta11 = beta_distribution(1,1,x)
beta55 = beta_distribution(5,5,x)
beta1010 = beta_distribution(10,10,x)

beta12 = beta_distribution(1,2,x)
beta56 = beta_distribution(5,6,x)
beta1011 = beta_distribution(10,11,x)

fig,ax = plt.subplots(1,3)
fig.set_size_inches(15,5)
ax[0].plot(beta11)
ax[1].plot(beta55)
ax[2].plot(beta1010)
plt.show()
fig.savefig("beta_1.png")

fig1,ax1 = plt.subplots(1,3)
fig1.set_size_inches(15,5)
ax1[0].plot(beta12)
ax1[1].plot(beta56)
ax1[2].plot(beta1011)
plt.show()
fig1.savefig("beta_2.png")